### ISSUE TITLE
Mockups sharing settings

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/twin_aydo#16]

**Comment by Baertie** [comment]
<img width="668" alt="Screenshot 2021-08-17 at 11 01 09" src="https://user-images.githubusercontent.com/44461137/129697167-9e16b98a-8bd3-4e5f-a9c9-b865c26ae0aa.png">
<img width="743" alt="Screenshot 2021-08-17 at 11 00 49" src="https://user-images.githubusercontent.com/44461137/129697195-d67e107a-411e-4d3f-892a-d9ce1de8a6c0.png">
