### ISSUE TITLE
[Quantum] file share move breaks

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/twin_aydo#191]
- [x] Browser is rendered wrong in AppLayout which breaks things for the socketStore
- [x] socket listener for 'updated shares'
- [x] update chat if share changes
- [x] if i share a file from my root dir and then move the file to a folder, then i click the original message i get redirected to root and should be the folder instead
- [x] Not connected with socket on path '/quantum/shared'

**Comment by JorisBassle** [comment]
Now you get 'fileDoesNotExist' error and infinite loading screen.
