### ISSUE TITLE
Can't add certain users as contact in Whisper

### ISSUE THREAD

**Issue by LennertDefauw1** [threefoldtech/twin_aydo#254]
Lennert007 wants to add lennar as contact but does not seem to appear in the add contact list

![image](https://user-images.githubusercontent.com/43674202/149155921-d8c928b0-9a39-49c8-9ff2-0fbbdafc731a.png)

Lennar wants to add Lennert007 as contact but does not seem to appear in the add contact list

![image](https://user-images.githubusercontent.com/43674202/149156090-8cf0a132-7d1f-4763-9d20-930f0b58267b.png)

Only lennyg78 seems to appear in the list related to my name.

HTTP get on this call returns the right information, maybe a wrong config?

https://login.staging.jimber.io/api/users/digitaltwin

**Comment by LennertDefauw1** [comment]
Lennert007 wants to add lennar as contact but does not seem to appear in the add contact list

![image](https://user-images.githubusercontent.com/43674202/149155921-d8c928b0-9a39-49c8-9ff2-0fbbdafc731a.png)


Lennar wants to add Lennert007 as contact but does not seem to appear in the add contact list

![image](https://user-images.githubusercontent.com/43674202/149156090-8cf0a132-7d1f-4763-9d20-930f0b58267b.png)


Only lennyg78 seems to appear in the list related to my name.

HTTP get on this call returns the right information, maybe a wrong config?

https://login.staging.jimber.io/api/users/digitaltwin

**Comment by LennertDefauw1** [comment]
Issue found:


![image](https://user-images.githubusercontent.com/43674202/149158353-363a6ca5-61ee-464b-9659-c311e6d232f6.png)


Call to get all DT contacts returning to the old staging (login.staging.jimber.org), new accounts are made on login.staging.jimber.io

**Comment by JorisBassle** [comment]
Was already fixed
![image](https://user-images.githubusercontent.com/36887810/157047309-99568bad-e1a2-428b-9617-ba070a022b6c.png)
