### ISSUE TITLE
Provide a error screen that some kind of filetypes not can be viewed / opened

### ISSUE THREAD

**Issue by LennertDefauw1** [threefoldtech/twin_aydo#273]
Uploaded file .flutter

Could double click and opened a new tab, but it is constantly loading
![image](https://user-images.githubusercontent.com/43674202/149315289-9ac6a1b8-6805-4c11-8a4d-607169099fe3.png)

Maybe provide a text that this kind of filetype cannot be opened / or just block the action that this file can be opened?

**Comment by JorisBassle** [comment]
Seems fixed, there was a small mistake in the vue file a while ago, this has resolved the issue probably.
