### ISSUE TITLE
[Glass] Settings

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/twin_aydo#310]
- [ ] Make toggles inline.
- [ ] Statistics should be a toggle and be inside settings.
- [ ] Clicking on a toggle should not exit the settings screen.
- [ ] It should be clear that you can open and close settings. Maybe with an arrow icon next to settings.
- [ ] If settings is open add more margin to the bottom
- [ ] If you hide the browser bar the hamburger icon should be at the top right of the screen. Same for when you are in the settings screen.
![image](https://user-images.githubusercontent.com/36887810/157259878-ca9f1620-b3ca-4a80-af1b-2bb5b0dc334e.png)

**Comment by ken-de-moor** [comment]
Not really room to change these things on uhuru level. Any changes should be asked in the browser project. This isn't part of the uhuru codebase.
