### ISSUE TITLE
[Flow][Frontend] Delete/Add user, Delete/Add messages

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/twin_aydo#312]
Deleting a user should remove contact and remove his posts from your feed. There should be a difference between 'delete user' and 'delete messages'

- [ ] Delete user (you don't have the user in your contact list anymore and don't see his posts).
- [ ] Add user (with connection request to the other user). You see his posts again if he accepts the request.
Extra button next to add messages to add users.
![image](https://user-images.githubusercontent.com/36887810/157428119-e97ee391-2374-4d58-800d-af5ea29573a9.png)
- [ ] Delete messages. You still see the posts of the user in your feed and still have him in your contact list.
- [ ] Add messages. (Without connection request, you can just add the chat again). Add a user should be replaced with 'add message'
![image](https://user-images.githubusercontent.com/36887810/157428456-02104f6e-ca7b-4ee7-9946-0644f67bc1e2.png)

**Comment by ken-de-moor** [comment]
@JorisBassle @EdwardKerckhof is this ticket still relevant?

**Comment by JorisBassle** [comment]
@ken-de-moor this has already been added into the refactor. You now have a separate list for contacts and chats. If you delete the chat you can still see the posts of the contact.
![image](https://user-images.githubusercontent.com/36887810/182128081-5805bf63-2a8b-4a35-b3d3-aecd545f5228.png)
