### ISSUE TITLE
[Flow][Backend] Delete/Add user, Delete/Add chat

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/twin_aydo#314]
See issue #312 for more info

- [ ] Delete user
- [ ] Add user
- [ ] Delete chat
- [ ] Add chat

**Comment by ken-de-moor** [comment]
@JorisBassle @EdwardKerckhof is this ticket still relevant?

**Comment by JorisBassle** [comment]
@ken-de-moor this has already been added into the refactor. You now have a separate list for contacts and chats.
![image](https://user-images.githubusercontent.com/36887810/182128081-5805bf63-2a8b-4a35-b3d3-aecd545f5228.png)
