### ISSUE TITLE
username is default selected instead of group name when creating group

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/twin_aydo#32]

**Comment by ken-de-moor** [comment]
Seem to just get a user list instead of group name stuff, when I start filtering I do get group name.

![image](https://user-images.githubusercontent.com/59569757/131306543-da1d9086-5171-450d-8717-068fa2a1a655.png)

Possibly not yet deployed and need to retest

**Comment by ken-de-moor** [comment]
Works with new deploy
