### ISSUE TITLE
[Whisper] Adding a new contact doesn't show the right avatar

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/twin_aydo#326]
It only uses default avatars until you have added the contact as a friend.
![image](https://user-images.githubusercontent.com/36887810/158614265-9bf2d3db-ef8a-482a-a571-e672408f94b4.png)

**Comment by ken-de-moor** [comment]
Only shows blank images right now, not even default anymore.

![image](https://user-images.githubusercontent.com/59569757/174619472-60e3010c-1978-4f97-be2b-7c616a2fbb23.png)

**Comment by Baertie** [comment]
Moest na tschijnt al lange closed zijn

**Comment by ken-de-moor** [comment]
Can't easily fix this as we need to ping every container for every image
