### ISSUE TITLE
[Quantum] Deleting shared files

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/twin_aydo#335]
- [x] If the owner deletes the file it should be removed from 'shared with me' for the other users...
- [x] And the shared message should be deleted too in Whisper.
- [x] Bug fix: If the owner shares a file it gets in his 'shared with me' map 
- [x] If you remove permissions of a user it doesn't get updated right away in this dialog...
![image](https://user-images.githubusercontent.com/36887810/162439615-b7f4c446-073c-4be3-a05d-ebeb3660c1bd.png)

- [x] If the owner removes all permissions for a user they still see the file under 'shared with me'. But the link doesn't work, this should be removed...
- [x] The message with the shared file should be removed too if the user has no more permissions.
- [x] Can't delete a file sometimes
- [x] If you share a file again with the same user it get's removed from his 'shared with me'
- [x] Sharing the same file multiple times keeps getting added to your own chat.
- [x] Modifying an existing share from read to write should replace it in your chat and the chat of the selected user

**Comment by ken-de-moor** [comment]
Story is a bit too big to functionally validate/close at once, will just close and we'll report separate bugs as needed.
