### ISSUE TITLE
Fix or hide titles

### ISSUE THREAD

**Issue by EdwardKerckhof** [threefoldtech/twin_aydo#358]
Tile view trekt echt op niet veel, ofwel moet je grotere tiles hebben zodat je alles kan lezen, ofwel moet het voorlopig gewoon uitgezet worden. De shared with me zien er daar ook uit als gewone tiles wat raar is. Ik zou gewoon button **hiden** voor nu.

**Comment by ken-de-moor** [comment]
Doesn't really seem fixed to me.

![image](https://user-images.githubusercontent.com/59569757/165538168-fbb66eb6-8708-47b8-937f-087e3a1d86d4.png)

**Comment by JonasWijne** [comment]
will be handled in v1.4 or v1.5 mobile redesign
