### ISSUE TITLE
Flow - When commenting on a deleted post it breaks and errors

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#373]
Made a post with user gillesm, it showed up in gillesm2's feed. Then deleted gillesm his post and tried to comment on it because it still showed up in gillesm2's feed. It got in a broken state with negative likes and a comment input field thats disabled after entering.
![deletedPost](https://user-images.githubusercontent.com/43674162/163146080-a36f9c67-0dc9-4fa6-9c80-ef68e34baed4.gif)
![image](https://user-images.githubusercontent.com/43674162/163146033-0990e84b-f0a3-4445-8f6f-24b4cdb25204.png)

**Comment by EdwardKerckhof** [comment]
Make sure deleted posts are also removed for other users without refresh (socket.io)
