### ISSUE TITLE
Whisper - messages not sending (corrupt container?)

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#374]
Made 2 new TF accounts. The request to message was not a problem but after accepting we are unable to see eachothers messages, only send them.
![image](https://user-images.githubusercontent.com/43674162/163148073-e4a40da6-9f8b-4378-a2db-7e801dcd19dc.png)

**Comment by EdwardKerckhof** [comment]
Happens only on initial docker spawn, after restart everything works as expected.
