### ISSUE TITLE
Flow - No character limit on comments which makes the UI overflow off screen

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#379]
![image](https://user-images.githubusercontent.com/43674162/163170257-1df2e129-3a99-40f5-b2b5-d10b29ce1656.png)

**Comment by Baertie** [comment]
Bij het instellen van een overflow zodat deze issue gefixt wordt breekt de pop up van de user.
Deze wordt afgesneden door de relative container deze issue hebben we al in verschillende projecten gehad.
Nu ga ik er wel goed voor kijken voor een oplossing.
