### ISSUE TITLE
Whisper - When editing a message and change chat to other person and back it says undefined

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#383]
The message preview is also empty after this.
![undefined](https://user-images.githubusercontent.com/43674162/163174391-49f1f035-d792-436c-8629-f92a3b2d2bb7.gif)

**Comment by ken-de-moor** [comment]
Now it says message not found instead of undefined, but should simply not be an issue in the first place. just clear the selection or make it work, but message not found isn't ok.

**Comment by ken-de-moor** [comment]
Only if it's an easy fix.

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/182091522-9b25d7b5-51cc-4262-b633-47d1cdbe3eaf.png)
