### ISSUE TITLE
Quantum - Uploading files with backslashes cuts of filename before the slashes

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#385]
The same happens with filenames from pictures sent in chats. Be sure to also check other 'illegal' characters altough i'm pretty sure its only these backslashes.

![cut](https://user-images.githubusercontent.com/43674162/163183364-8c881230-8f63-41f4-93b9-dc0cd74d2318.gif)

**Comment by JorisBassle** [comment]
@Baertie this will probably get fixed with issue #395
