### ISSUE TITLE
Whisper - I'm able to upload zipped files that are larger than the file limit

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#389]
Also works with .deb files.
![kanye](https://user-images.githubusercontent.com/43674162/163192943-b4008a78-9550-4594-a528-0967ff572c83.gif)
UPDATE: Downloading these files crashes the container. Updating this issue to major.
![containerCrash](https://user-images.githubusercontent.com/43674162/163195417-07314216-c5a2-4667-a1bd-6f8d52c899d1.gif)

**Comment by JorisBassle** [comment]
fixed with #387 
![image](https://user-images.githubusercontent.com/36887810/163569040-a063ca06-8047-4027-8e46-9742ad6478ee.png)
