### ISSUE TITLE
Rounded borders on sent voice messages

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/twin_aydo#39]
![image](https://user-images.githubusercontent.com/17977313/129877264-f9c0c382-0cb0-4a01-a112-798398e0a54a.png)

**Comment by JonasWijne** [comment]
![image](https://user-images.githubusercontent.com/6184820/130443921-28b3d46e-c503-4864-b1f8-6cc81dc5c978.png)
slightly improved
