### ISSUE TITLE
Quantum - When creating a folder with special characters downloading/copy pasting files errors

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#395]
The name i have my folder was zéeuygfzeiuyf\\\«««|@"²''\\"&éeeeeeee. Can also not download these special folders as a whole.
![folderNaming](https://user-images.githubusercontent.com/43674162/163213059-573a1375-ea18-4ef5-ae14-f95d0cda65ed.gif)

**Comment by ken-de-moor** [comment]
Always remember to also include edit flow. When you have to implement any kind of validation on a create, the same validation should exist for the edit, otherwise it can be bypassed.
