### ISSUE TITLE
Quantum - File upload % always goes from 0 to 100% with nothing in between.

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#396]
They all jump to 100% at once and they don't gradually progress. Could be browser too?
![progressionToast](https://user-images.githubusercontent.com/43674162/163214446-0c735861-171c-49f9-8a19-7b5fc17ec50a.gif)

**Comment by ken-de-moor** [comment]
Also happens with single files. Seems only states are 0% and 100%

**Comment by ken-de-moor** [comment]
Only fix if it's an easy fix.
