### ISSUE TITLE
Quantum - renaming a file to an extremely long name it does nothing

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#397]
It just stays the same name. Maybe also limit this or at least give a notification but don't leave the user in the dark. 
NOTE: An empty field is also possible please test the validation
EDIT: It just takes really long and then times out.
![image](https://user-images.githubusercontent.com/43674162/163215859-6c21b0c1-65e6-4859-aa1d-6f658f189db0.png)

**Comment by JorisBassle** [comment]
Also added notification for when the file rename fails
![image](https://user-images.githubusercontent.com/36887810/163573282-1fc8657f-0097-4618-b8b4-72ad13ecb82a.png)
