### ISSUE TITLE
Quantum - Cannot search in 'shared with me' and 'saved attachments'

### ISSUE THREAD

**Issue by GillesMommerency** [threefoldtech/twin_aydo#399]

**Comment by ken-de-moor** [comment]
Only fix if it's an easy fix. Max 2 hours work.

**Comment by ken-de-moor** [comment]
Works in saved attachments but not in shared with me.
![msedge_rrAlDJ6yOk](https://user-images.githubusercontent.com/59569757/183657942-f9953f07-c72d-43f5-9ea6-ee2ca09c80e3.gif)
