### ISSUE TITLE
Clicking the Uhuru logo doesn't do anything 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/twin_aydo#429]
**Describe the bug**
Top left Uhuru button doesn't do anything when clicked. 

**Expected behavior**
Should there be a home screen of Uhuru? 

**Screenshots**
![Screenshot 2022-04-25 at 14 25 06](https://user-images.githubusercontent.com/31733464/165088474-e4b60638-294b-48c1-a370-9622a13b9ade.png)

- Operating system:
 - Browser: Google Chrome

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/165695847-87fce04f-b324-44bb-b2a6-1112bd6f61a9.png)
