### ISSUE TITLE
Whisper - Can't find users / can't be found 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/twin_aydo#431]
**Describe the bug**
Trying to add baertarno - lennertapp2 but getting 'no matching results' 
Other way around as well when they try to add me (sabrinasadik)

**To Reproduce**
1. Go to Whisper
2. Click on + Messages
3. Add a user - type baertarno or lennertapp2
4. Getting 'No matching results'

**Expected behavior**
Finding users

**Screenshots**
![Screenshot 2022-04-25 at 15 12 05](https://user-images.githubusercontent.com/31733464/165096553-deaf0877-0c8b-4763-af6f-48cd8573cc37.png)
 
- Operating system:
 - Browser: Google Chrome

**Comment by JensMeire** [comment]
Fout in Uhuru. Fout in config voor url naar backend voor de app waardoor je niet geregistreerd werd.
