### ISSUE TITLE
Whisper - online status incorrect

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/twin_aydo#438]
**Describe the bug**
Shows status of other person as offline while I'm chatting with them. 

**To Reproduce**
1. Go to Whisper
2. Click on any contact person
3. Start chat
4. Person is shown as offline 

**Expected behavior**
Should show correct online/offline status

**Screenshots**
<img width="539" alt="Screenshot 2022-04-27 at 13 33 26" src="https://user-images.githubusercontent.com/31733464/165509303-de9a2efc-0261-4e49-9a15-9873d24881b4.png">

 - Browser: Google Chrome

**Additional context**
Shows all contacts as offline

**Comment by JorisBassle** [comment]
more info #370
