### ISSUE TITLE
[Frontend/Backend] Change all frontend REST calls to websockets

### ISSUE THREAD

**Issue by EdwardKerckhof** [threefoldtech/twin_aydo#448]
- [x] Yggdrasil location
- [x] Blocked contacts
- [ ] Status
- [ ] Chats
- [ ] Authenticated

**Comment by ken-de-moor** [comment]
@JorisBassle @EdwardKerckhof 

What is the state here, is this still something we want and need to do? Is this a priority thing? If we still want to do it what is the expected effort and result?
