### ISSUE TITLE
Small changes to initial landing page.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#46]
- [x] Remove john doe placeholder, just no placeholder value.
- [x] Remove the background with the pattern, just make it white or a very light grey.

![image](https://user-images.githubusercontent.com/59569757/130081425-f339ed6d-43c8-4332-bf83-c6d73bf594af.png)

**Comment by ken-de-moor** [comment]
Not included in this deploy it seems.

**Comment by tobiaschielens** [comment]
Spawner will disappear as the deploy will be done in flists

**Comment by Baertie** [comment]
I have done this but see the comment of Tobias
