### ISSUE TITLE
Whisper - implement link preview

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/twin_aydo#474]
![image](https://user-images.githubusercontent.com/6184820/168255143-73807cfe-c71b-46ec-90e2-c40c556dd413.png)
![image](https://user-images.githubusercontent.com/6184820/168255176-9e15eb24-bf86-491f-9b82-1202710a401d.png)

**Comment by ken-de-moor** [comment]
Re-opened, should be disabled for V1.4

Tested top 5 most visited sites.

Not a single one previewed correctly.

![image](https://user-images.githubusercontent.com/59569757/180435586-681206bd-5bae-4212-b46e-1bb5b7616c37.png)

**Comment by Baertie** [comment]
![Screenshot 2022-07-25 at 11 22 42](https://user-images.githubusercontent.com/44461137/180744486-d0ad023e-851e-4a5e-8eaa-a9f748f98c42.png)

Bug is gefixt maar we zetten het toch nog in commentaar en pakken het mee naar V1.5 om wat perfomance issues te fixen
