### ISSUE TITLE
Accessing Uhuru on mobile does not work 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/twin_aydo#481]
**Describe the bug**
Trying to go to https://sabrinasadik.beta.uhuru.me on my phone, white page, nothing happens. 

**Screenshots**

https://user-images.githubusercontent.com/31733464/168256043-ef0c7383-b617-4473-8262-d5b7a287efca.MP4

**Device (please complete the following information):**
I read that we shouldn't submit bugs about mobile exp, but @JonasWijne told me it's possible to use Uhuru on mobile. If this doesn't work, we can't start using it between us. 
*Please don't submit bugs about mobile experience, currently our focus is on desktop experience.*
 
- Operating system: iOS

**Comment by ken-de-moor** [comment]
Known, no safari support yet.

Followup here : https://github.com/threefoldtech/twin_aydo/issues/544
