### ISSUE TITLE
@name in groupchat

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/twin_aydo#482]

**Comment by ken-de-moor** [comment]
Tab doesn't work to select one, clicking doesn't work to select one either.

**Comment by ken-de-moor** [comment]
Feature should be either fixed or disabled, not to be left in current state.

**Comment by ken-de-moor** [comment]
- Tab still doesn't work to select one.
- Also the name is always highlighted even though it's not actually me being referenced.

![image](https://user-images.githubusercontent.com/59569757/182090156-8d52acef-149b-4aed-9b81-d5e3632c243f.png)

**Comment by ken-de-moor** [comment]
For edward: we has a videochat how to solve.

Also fix the contrast.
