### ISSUE TITLE
No authentification popup in app when logging into Uhuru

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/twin_aydo#494]
**Describe the bug**
Trying to login to Uhuru - not getting an authentification pop up. When I click resend, it appears in the app and I can login. Tried multiple times over the last few weeks, always the same result. Can login after pressing 'resend'

-   Operating system: iOS 15.4.1
-   Browser: Google Chrome
- Username: sabrinasadik

**Comment by ken-de-moor** [comment]
@sabrinasadik does this still happen? I can't reproduce at all here.

**Comment by JorisBassle** [comment]
Tried with the app already open or closed and works both times for me.
