### ISSUE TITLE
Uhuru login redirects to blank screen

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/twin_aydo#506]
Tried logging in to Uhuru on the main login page on https://beta.uhuru.me/

and just getting a blank screen after the redirect

![image](https://user-images.githubusercontent.com/65153287/169297818-06b710a8-f2b3-4554-9150-a9e155e6f5f7.png)

![image](https://user-images.githubusercontent.com/65153287/169297669-c930ce04-9b06-4801-a67d-d8af2d90f06c.png)

**Comment by EdwardKerckhof** [comment]
Known issue: https://github.com/threefoldtech/twin_aydo/issues/302
