### ISSUE TITLE
Add user to group not working.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#510]

**Comment by JorisBassle** [comment]
Can not reproduce bug, and tried different ways to add the user to the group

**Comment by ken-de-moor** [comment]
Still doesn't work atm. Tried clicking in many different places nothing seems to do anything. Only time I can add users is during initial group creation, then after that it fails.



![S548z8XJSD](https://user-images.githubusercontent.com/59569757/174821008-fbc4c4e6-c4fc-4452-837d-e210fa8f2ae9.gif)

**Comment by JorisBassle** [comment]
Just tested and I can add users on staging
