### ISSUE TITLE
Flow - Both previously posted pictures as newly posted pictures can not be seen

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/twin_aydo#521]
**Describe the bug**
Can't see any pictures I posted before. Tried posting a new pic, can't see anything. 

**Screenshots**
![Screenshot 2022-06-16 at 15 03 21](https://user-images.githubusercontent.com/31733464/174075984-599fc0c9-4215-453d-85da-53753aee5c31.png)

**Comment by ken-de-moor** [comment]
Resolved in staging
