### ISSUE TITLE
Newly created 3bot account, refusing to log in on uhuru.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#524]
1) Created the new account kekekek.3bot
2) Try to login.

I keep being redirected instead of logging in, tried in same browser with a different account and it does work, it's purely the new account that doesn't work.

![ACR7jetLSR](https://user-images.githubusercontent.com/59569757/174611818-5839cb14-a287-48fa-8ec0-c9570ac234d8.gif)

**Comment by ken-de-moor** [comment]
Created another account kenk.3bot, same issue. Stuck on validating v1.3 for now.

**Comment by JorisBassle** [comment]
@ken-de-moor fixed issue. Will be pushed on staging
