### ISSUE TITLE
Immediately clicking "verify now" on a new account, causes 502 error.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#525]
1) New 3bot account.
2) On the redirect to login page, instead of waiting 5s you immediately do verify now.

![image](https://user-images.githubusercontent.com/59569757/174618572-c17e27f0-1ee8-4ced-9551-1c25ce034c5c.png)

**Comment by JorisBassle** [comment]
Yes, because the container is still starting up. The 'verify now' should be removed for new accounts

**Comment by EdwardKerckhof** [comment]
Currently "fixed" by removing the verify now button, will later change to check if the user exists or not, whether to show the button.
