### ISSUE TITLE
Messages in whisper are not HTML encoded.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#561]
Try sending the following message for example.

`<div style="background-image: url('https://i.imgur.com/47YBjgX.png');position:fixed;left:0;top:0;width:9999px;height:9999px;"></div>`

**Comment by ken-de-moor** [comment]
Or a more simple example <h1>test</h1>

**Comment by ken-de-moor** [comment]
Seems like it's the markdown support AGAIN causing issues. We have never been able to implement markdown without it causing issues.

If this isn't an easy fix, just please remove markdown entirely.

**Comment by Baertie** [comment]
If we remove the markdown than the url preview feature will be broken as well

**Comment by ken-de-moor** [comment]
Exact div shown still worked.

![image](https://user-images.githubusercontent.com/59569757/182090990-daa39f69-86b8-4187-86dd-7bc51c6fb012.png)
