### ISSUE TITLE
Retry contact requests

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#581]
Situation:

User A sends user B A request, but user B hasn't logged in yet and has no container spawned.

We should have a system where if a user logs in for the first time, it should fetch all open requests.

Also, these requests have often not arrived for reasons we still aren't sure about. We should just have retry systems in case this happens again.

We need to think differently here than the normal system with central databases, and need more retry systems.

Plan:
- [x] Send a contact request and check if the endpoint is reachable.
- [x] If the endpoint is unreachable, add IPv6 together with request parameters to an array of unsuccessful requests.
- [x] Setup a CRON job in Nest that pings these locations every few seconds.
- [x] If the ping was successful: resend the request and remove the entry from the array, if not try the next entry. 
- [x] Repeat until the array of unsuccessful requests is empty.
- [x] Ping like 5 times on a 5 second interval. If not a single one of those gets a reply, start pinging only every half an hour or so.
- [x] Add to redis instead of server memory

**Comment by EdwardKerckhof** [comment]
1. Send a contact request and check if the endpoint is reachable.
2. If the endpoint is unreachable, add IPv6 together with request parameters to an array of unsuccessful requests.
3. Setup a CRON job in Nest that pings these locations every few seconds.
4. If the ping was successful: resend the request and remove the entry from the array, if not try the next entry. 
5. Repeat until the array of unsuccessful requests is empty.

**Comment by EdwardKerckhof** [comment]
@ken-de-moor how frequent should there be pinged? And after how many hours/days should the failed array be cleared?

**Comment by EdwardKerckhof** [comment]
@ken-de-moor everything sounds good but for the ones that have not replied in 7 days, it is tricky to try and ping them on startup since this would only be on a new build. Another option is to retry every month or so.

**Comment by EdwardKerckhof** [comment]
Also, this: `On a new session/login/whatever, reset the 5 times every 5 seconds so it tries everyone again.` is impossible to do because when the container eventually starts it has no idea who tried contacting it so it can not ping the one who tried.

**Comment by ken-de-moor** [comment]
Very hard to test right now, will just leave untested and see what happens in prod.
