### ISSUE TITLE
QUANTUM - Can't copy files

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/twin_aydo#591]
Route does not yet exist
![image](https://user-images.githubusercontent.com/36887810/181292577-7c0427b5-f285-4f04-a5d5-987eb8a229d5.png)

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/182091854-68b6ae41-fc43-487a-99a3-3a3ef155ce50.png)
