### ISSUE TITLE
Remove the manual contact adding option.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#597]
Talking about the one in advanced.

It causes a lot of bugs and a user has no clue what to input here anyway.

Unless anyone can tell me why it needs to exist? Then we can try to fix the bugs if it's really needed.

![image](https://user-images.githubusercontent.com/59569757/182091265-9beb34d4-55f6-4a2c-8de0-ea9abd306d07.png)

**Comment by EdwardKerckhof** [comment]
This is used primarily in development. We can hide this when in staging/prod.
