### ISSUE TITLE
Flow - Double posting.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#599]
![chrome_keHZk9iy6H](https://user-images.githubusercontent.com/59569757/182093744-c87a5c17-8206-4e5d-b4d4-9eaef289e4e2.gif)

**Comment by EdwardKerckhof** [comment]
@ken-de-moor how can this be reproduced?

**Comment by ken-de-moor** [comment]
@EdwardKerckhof didn't really do anything special, I just noticed it happening.

I was testing many things on flow at the time, commenting on other posts, likes, sharing posts... I pretty much tried all the features. Then after scrolling through my feed I noticed all my recent posts were doubled.
