### ISSUE TITLE
Favicon is still uhuru => Change to Freeflow.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#637]

**Comment by EdwardKerckhof** [comment]
Which favicon exactly? The one in spawner has been handled in [this issue](https://github.com/threefoldtech/twin_aydo/issues/633) and will be fixed next release. 

In the app, I have the correct favicon.

![image](https://user-images.githubusercontent.com/47602885/183050801-65d71da7-3881-4958-9d00-a0266653596e.png)

**Comment by ken-de-moor** [comment]
Was caching apparantly
