### ISSUE TITLE
Flow - Comment input auto-focus is gone

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/twin_aydo#648]
If you click on the 'comment' button of a Post it gives focus so you can start typing right away. But it only does this the 1st time, should be every time you click on the button.

How to reproduce:
- Create a post
- Click on 'comment' button
- Add a comment
- Create another post
- Click on 'comment' button
It does not auto-focus now

**Comment by Baertie** [comment]
That is normal behavior of auto focus.
Auto-focus only works on first render. So when clicking on comments again the focus is gone and will not come back.
So we have to find another solution for this
