### ISSUE TITLE
Flow - Remove 3 dots if not own Post

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/twin_aydo#649]
I can still click on the 3 dots of someone else his post but it gives nothing.
Only hide this on desktop for when a post is not yours. On mobile show again because the option to share is put in that component.
![image](https://user-images.githubusercontent.com/36887810/183345653-97052dac-2862-47c4-9169-350bcf716b3d.png)

**Comment by Baertie** [comment]
Enkel niet showen als post niet van u is op desktop in mobile komt share in die 3 puntjes
