### ISSUE TITLE
Quantum - Handle shared files not being able to download

### ISSUE THREAD

**Issue by EdwardKerckhof** [threefoldtech/twin_aydo#683]

**Comment by ken-de-moor** [comment]
1) As person A, shared a .deb file ( can't be displayed in onlyoffice )
2) As person B, open this file, it tells me to download it instead

![image](https://user-images.githubusercontent.com/59569757/183652708-97d2ab20-7621-41ba-87bc-c9fc54aa0f88.png)

When I open it, I get this

https://typen.digitaltwin-test.jimbertesting.be/api/v2/external/resource?loc=https%3A%2F%2F%5B205%3Abe49%3A57d1%3A49ce%3A5a60%3Ae3ae%3A4db6%3A15fc%5D%2Fapi%2Fv2%2Fquantum%2Ffile%2Finternal%3Fpath%3D%252Fappdata%252Fstorage%252FThreeFoldPlanetaryNetwork-v0.2-RC3-x64-Linux.deb%26token%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaWxlIjoiL2FwcGRhdGEvc3RvcmFnZS9UaHJlZUZvbGRQbGFuZXRhcnlOZXR3b3JrLXYwLjItUkMzLXg2NC1MaW51eC5kZWIiLCJwZXJtaXNzaW9ucyI6WyJyIl0sImlhdCI6MTY2MDA0OTk0NiwiZXhwIjoxNjYwMDUwMjQ2LCJhdWQiOiJxdWFudHVtIiwiaXNzIjoia2VuZGFsZiJ9.MtgPBo6JnboXwWBn1WCskSWTmhPrtF155a_2v1PzNIc%26attachment%3Dfalse

![image](https://user-images.githubusercontent.com/59569757/183652916-37c0457d-26ae-4a3b-af9c-bf82e6a17fb8.png)

When doing the same download as the file owner, it does work.
