### ISSUE TITLE
First login doesn't work.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#69]
Hard to reproduce, but easiest seems to be doing a full incognito new browser with a new user.

First login, where you fill your name in, and press enter. It doesn't seem to do anything sometimes, then second enter it works.

**Comment by JonasWijne** [comment]
first gut feeling is that yggdrasil is starting up, there is a 30 second window where yggdrasil can  startup and give an ip, this could be an explanation.

have to check tho

**Comment by ken-de-moor** [comment]
Just had it again for an existing user "kentyy", but after not visiting the DT for a while.

Not sure if that confirms the theory or not.
