### ISSUE TITLE
Shared with me is empty after sharing gif, error in console.log

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#70]
1) On my user kentyy, I shared a gif with user kiik
2) On user kiik I browser to shared with me

![image](https://user-images.githubusercontent.com/59569757/131319513-0258cf84-c788-4721-8cba-8e8d327a117e.png)

**Comment by jdelrue** [comment]
check?

**Comment by ldruwel** [comment]
cannot reproduce
