### ISSUE TITLE
[QUANTUM][WHISPER] Edit text files, make list of extensions

### ISSUE THREAD

**Issue by EdwardKerckhof** [threefoldtech/twin_aydo#730]
html editing without onlyOffice for simple files (txt, js, json, markdown,...)

- [x] Implement in Quantum
- [x] Edit shared files
- [x] Implement in Whisper
- [x] Use readOnly view for read shares
- [x] Make mobile friendly
- [x] extra save button with the editor

**Comment by sasha-astiadi** [comment]
on staging, will check it myself , good for forum @sasha-astiadi
