### ISSUE TITLE
Unclear instructions on self deploy ( username missing ) - See comments

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/twin_aydo#74]
- [x] Rebrand the whole thing to Uhuru

- [x] Add "Do you want to run the decentralized Uhuru machine on your own machine?" opens popover with:

You can also try out the beta Uhuru experience on your own device by running this command:
1. Install Docker
2. Run your own Uhuru environment inside a Docker:
```
docker run -ti --sysctl net.ipv6.conf.all.disable_ipv6=0 -e "USER_ID={{USERNAME}}" -e "DIGITALTWIN_APPID=digitaltwin-local.jimbertesting.be" -e "ENVIRONMENT=staging" --cap-add=NET_ADMIN --device=/dev/net/tun:/dev/net/tun  -p 443:443 threefoldjimber/digitaltwin:latest
```
3. Browse to https://{{username}}.digitaltwin-local.jimbertesting.be
5. Replace {{USERNAME}} with your own name.

**Comment by scottyeager** [comment]
A tester has commented that the instructions for self deployment are confusing. Reviewing here, it looks the issue with `{{username}}` getting filtered out was not actually resolved.

Currently at beta.uhuru.me:

![image](https://user-images.githubusercontent.com/17682591/176250848-e11ba193-d407-4dbc-88d1-f2531f351230.png)

**Comment by ken-de-moor** [comment]
Username still missing.

![image](https://user-images.githubusercontent.com/59569757/182090814-14309318-c321-451f-bdca-94b8e91e0e3a.png)

**Comment by EdwardKerckhof** [comment]
Is fixed but we need to wait until this issue is finished: https://github.com/threefoldtech/twin_aydo/issues/617
