### ISSUE TITLE
[SPAWNER] Sometimes when putting in your personal url you get redirected to the spawner where you have to fill in your username again.

### ISSUE THREAD

**Issue by Baertie** [threefoldtech/twin_aydo#757]
sometimes when putting in your personal url you get redirected to the spawner where you have to fill in your username again. Only after filling in your username again the personal url works.

This is also a problem for the freeflow app.

**Comment by JorisBassle** [comment]
Problem occured when your container was offline. We fixed it now by spawning the container if it is offline.
