### ISSUE TITLE
Onlyoffice sometimes refuses to load.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#771]
IMPORTANT EDIT: Same issue happens on production as the staging onlyoffice is shared! Onlyoffice is broken right now on production.

The problem is I don't have clear repro steps, however as I was testing on two accounts I've had it multiple times for each account, several times for the same files that worked before. Then 10 minutes later they magically work again.

I've had this happen about 2 times per hour or so, never being able to fix it with refreshing, but by just ignoring the issue and trying again half an hour later it resolves itself. Extremely weird

But then it just breaks again at a random time later. 

I'd say all around it happened 10+ times over the course of 1 day, so it's definitely much too frequent.

Log results on onlyoffice :

![image](https://user-images.githubusercontent.com/59569757/193898336-96b049cc-debb-4f89-ad62-ce00f6d89e19.png)

![msedge_sz3ttExFsz](https://user-images.githubusercontent.com/59569757/193898368-5341b1cc-d122-4341-b56d-1472c8fa5e73.gif)

**Comment by JorisBassle** [comment]
Tested beta and staging multiple times today, worked every time so far after the fix of @LennertDefauw1 .
