### ISSUE TITLE
Include Kutana

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/twin_aydo#79]
- [x] Add Kutana to the left menu -> freeflow connect interface
- [x] Give video app the same colors as Uhuru
- [x] Rename freeflow connect to Kutana (host on other domain should fix this - kutana.uhuru.me for instance

**Comment by jdelrue** [comment]
still in progress?

**Comment by jdelrue** [comment]
Please check with @MathiasDeWeerdt on thursday.

**Comment by MathiasDeWeerdt** [comment]
Done https://kutana.uhuru.me
